version: '3'
services:
  postgres: 
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - '5435:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql

  app:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: compcheck
    ports:
      - '3000:3000'
